---
version: '3'

services:
  mongoDB:
    image: mongo:latest
    container_name: mongoDB
    restart: always
    ports:
      - ${DATABASE_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379

